import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Menu from './components/menu'
import Search from './components/search'

let api = `https://kitsu.io/api/edge/anime?filter[text]=`;


export default function Home() {
  const [text, setText] = useState('');
  const [info, setInfo] = useState({});
  
  useEffect(() =>{
      if(text){
          console.log(text);
          fetch(`${api}${text}`).then((response) => response.json())
          .then((response) =>{
              setInfo(response);                                          
          }) 
      }
  },[text])


  return (
  <>
  <Menu />

  <div className="content">
        <Head>
          <title>Animes Catalog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Search 
                className="boxtext" 
                type="search" 
                value={text} 
                placeholder="Search" 
                onChange={(search) => setText(search)}/>

        <main className={styles.main}> 

             {info.data && (
                       <ul className="anime-list">                    
                          {info.data.map((anime) =>(
                               <li key={anime.id}>
                                   
                                        <img src={anime.attributes.posterImage.small} 
                                        alt={anime.attributes.canonicalTitle} />
                                        <h3>{anime.attributes.canonicalTitle}</h3>                                       
                                   
                               </li>
                          ))}
                       </ul>
                   )}   
      
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
  
  </>   
  )
}
