import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

j
import axios from 'axios'
import { useState } from 'react/cjs/react.production.min'

export default function Home() {
  const [anime,setAnimes] = useState({})

  useEffect(() =>{
    fetch(`https://kitsu.io/api/edge/anime?page[limit]=20&page[offset]=0`)
    .then((response) => response.json())
    .then((response) =>{        
        setAnimes(response);                  
    })
}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

       <h1>{anime.attributes.cannonicalTitle}</h1>
    
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
